Work with entities and repos
BlazeOfSoul/RafRate pull request #23
Opened 2022-10-02 17:59 UTC by BlazeOfSoul

2022-10-02 18:25 UTC, yarmoliq requested changes

2022-10-02 18:25 UTC, yarmoliq commented on server/RafRate.API/Controllers/ActiveDayController.cs
> +    public ActiveDayController(ActiveDayService activeDayService) => this._activeDayService = activeDayService;
Revert this.
What happens when you add a new dependency?

2022-10-02 18:25 UTC, yarmoliq commented on server/RafRate.API/Controllers/AuthenticationController.cs
> +using Data.Entities.Users;
Why is this `using` separated from other usings?

2022-10-02 18:25 UTC, yarmoliq commented on server/RafRate.API/Controllers/CommentController.cs
> +    public CommentController(CommentService commentService) => this._commentService = commentService;
Revert

2022-10-02 18:25 UTC, yarmoliq commented on server/RafRate.API/Controllers/TeacherController.cs
> +    public TeacherController(TeacherService teacherService) => this._teacherService = teacherService;
Revert

2022-10-02 18:25 UTC, yarmoliq commented on server/RafRate.Data/Entities/Teachers/TeacherEntity.cs
> +    public string JobTittle { get; set; }
Title misspelled

2022-10-02 18:25 UTC, yarmoliq commented on server/RafRate.Data/Interfaces/IBaseRepository.cs
> +    Task<TEntity> GetByAsync(Expression<Func<TEntity, bool>> expression, params Expression<Func<TEntity, object>>[] includes);
Дима, ты ему подсунул это?

2022-10-02 18:25 UTC, yarmoliq commented on server/RafRate.Data/Repositories/Base/BaseRepository.cs
> +        var newEntity = await _context.AddAsync(entity);
Should probably rename `newEntity` to smth like `entry`

2022-10-02 18:25 UTC, yarmoliq commented on server/RafRate.Data/Interfaces/IBaseRepository.cs
> +    Task<TEntity> GetByAsync(Expression<Func<TEntity, bool>> expression, params Expression<Func<TEntity, object>>[] includes);
Надо это обсудить, важно

2022-10-02 18:26 UTC, BlazeOfSoul commented on server/RafRate.Data/Interfaces/IBaseRepository.cs
> +    Task<TEntity> GetByAsync(Expression<Func<TEntity, bool>> expression, params Expression<Func<TEntity, object>>[] includes);
Please speak english i don't understand hahahhaha

2022-10-03 15:35 UTC, bogomazdmitry requested changes

2022-10-03 15:35 UTC, bogomazdmitry commented on server/RafRate.API/Controllers/AuthenticationController.cs
> +        this._authenticationService = authenticateService;
`This` is not required

2022-10-03 15:35 UTC, bogomazdmitry commented on server/RafRate.API/Program.cs
>          policy.WithOrigins("http://localhost:4200").AllowAnyMethod().AllowAnyHeader();
I think localhost url is not ok

2022-10-03 15:35 UTC, bogomazdmitry commented on server/RafRate.Data/Entities/ActiveDays/ActiveDayEntity.cs
> +public class ActiveDayEntity : IEntity
If you use Guid in every entity I think you can move id property to the base class

2022-10-03 15:35 UTC, bogomazdmitry commented on server/RafRate.Data/Interfaces/IBaseRepository.cs
> +    Task<TEntity> GetByAsync(Expression<Func<TEntity, bool>> expression, params Expression<Func<TEntity, object>>[] includes);
https://metanit.com/sharp/entityframeworkcore/3.9.php

2022-10-03 16:28 UTC, merged