Body
BlazeOfSoul/RafRate pull request #3
Opened 2022-08-04 12:57 UTC by dEISOT

hot fix

2022-08-04 16:19 UTC, BlazeOfSoul requested changes

2022-08-04 16:19 UTC, BlazeOfSoul commented on RafRate.API/Controllers/EventController.cs
> +    public class EventController : ControllerBase
I think better to use "Holiday" not "Event", structure "Event" is already exist in C#
Please change it in other places

2022-08-04 16:19 UTC, BlazeOfSoul commented on RafRate.Core/Services/CommentService.cs
> +    public class CommentService
add : ICommentService

2022-08-04 16:19 UTC, BlazeOfSoul commented on RafRate.Core/Services/AuthenticationService.cs
> +using System;
Bad tone - leave "using" that are not used in this file 
Fix in all files and in future use this "usings" only when you use something from this library

2022-08-04 16:39 UTC, bogomazdmitry commented on RafRate.API/Extentions/ServicesExtentions.cs
> +    public static class ServicesExtentions
Better to rename class, because you add not only service in this scope

2022-08-04 16:39 UTC, bogomazdmitry commented on RafRate.Data/Repositories/Base/BaseRepository.cs
> +    public abstract class BaseRepository<TEntity, TContext> : IRepository<TEntity>
Are you sure that TContext is needed?

2022-08-04 16:39 UTC, bogomazdmitry commented on RafRate.API/Extentions/AppExtentions.cs
> +    public static class AppExtentions
It is a bad name for the class where you only add exception handler

2022-08-04 16:39 UTC, bogomazdmitry commented on RafRate.API/Extentions/AppExtentions.cs
> +    public static class AppExtentions
If I sew this in code, I didn't understand what is it and why this handler in this class

2022-08-08 15:39 UTC, bogomazdmitry approved these changes
Great!

2022-08-08 15:43 UTC, merged